name: Deploy Latest Images on DST via Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code from the repository
        uses: actions/checkout@v3

      # Step 2: Extract the server IP
      - name: Extract Server IP
        id: extract_ip
        run: |
          SERVER_IP=$(grep -oP 'default *= *"\K[^"]*' infra/terraform/variables.tf | head -n 1)
          echo "SERVER_IP=${SERVER_IP}" >> $GITHUB_ENV

      # Step 3: Set up SSH with the private key
      - name: Set up SSH with private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DST_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts

      # Step 4: Copy script to server
      - name: Copy script to server
        run: |
          echo "Copying script to server with IP: ${{ env.SERVER_IP }}"
          scp -o StrictHostKeyChecking=no infra/scripts/deploy-on-dst.sh ubuntu@${{ env.SERVER_IP }}:/home/ubuntu/

      # Step 5: Run script via SSH
      - name: Run script via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@"${{ env.SERVER_IP}}" 'bash -s' < /home/ubuntu/deploy-on-dst.sh
